services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  mqtt-explorer:
    image: smeagolworms4/mqtt-explorer
    hostname: DESKTOP-0LM0OLQ
    container_name: mqtt-explorer
    ports:
      - "4000:4000"
    depends_on:
      - mqtt-broker
